defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - lr_monitor
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

#early_stopping:
#  monitor: "val_loss"
#  patience: 20
#  mode: "min"

model_summary:
  max_depth: -1

lr_monitor:
  logging_interval: 'step'
